/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package citebucket;

import citebucket.frontend.Splash;
import citebucket.util.AppState;

public class App {
    public static App INSTANCE = new App();
    AppState state = AppState.SPLASH;
    

    public static void main(String[] args) {
    }

    public App() {
        switch (state) {
            case SPLASH:
                String path = Splash.showSplash();
                state = AppState.BUCKET;
                break;
        
            case BUCKET:
                //load and create the bucket and then pass to the frontend

                break;
        }

    }
}
